name: file_tree_hasher
description: A new Flutter project.
publish_to: "none"
version: 1.0.1+4

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  percent_indicator: ^4.0.1
  crypto: ^3.0.3
  convert: ^3.1.1
  file_picker: ^6.0.0
  csv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  windows:
    generate: true
    image_path: assets/img/logo.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/img/logo.png
  web:
    generate: true
    image_path: assets/img/logo.png
