name: file_tree_hasher
description: Hash generation and comparison tool
publish_to: "none"
version: 2.0.0+2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.0.1
  file_picker: ^8.0.6
  csv: ^6.0.0
  crypto: ^3.0.3
  path: ^1.9.0
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  windows:
    generate: true
    image_path: assets/img/logo.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/img/logo.png
  web:
    generate: true
    image_path: assets/img/logo.png
