name: file_tree_hasher
description: A new Flutter project.
publish_to: "none"
version: 0.0.0+6

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  percent_indicator: ^4.0.1
  crypto: ^3.0.3
  convert: ^3.1.1
  file_picker: ^5.3.0
  csv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
