#!/bin/bash

branch_switched=$3

if [[ $branch_switched != '1' ]]
then
    exit 0
fi

echo "----- POST CHECKOUT -----"

# Get name of checked out branch
current_branch=$(git rev-parse --abbrev-ref HEAD)

# Get root directory
root_dir="$GIT_DIR/.."

if [[ $current_branch == release/* ]]
then
    echo "Remove example files from app"
    sed -i 's/\[_exampleFileTree\]/[]/' $root_dir/flutter_app/lib/templates/contentarea.dart
    sed -i 's/\[_exampleFile\]/[]/' $root_dir/flutter_app/lib/templates/contentarea.dart

    echo "Commit removed example files"
    git add $root_dir/flutter_app/lib/templates/contentarea.dart
    git commit -m "<hook> removed example files from release branch"
fi

echo "--- POST CHECKOUT END ---"
