# Build the app for Windows, Linux and macOS

name: build and deploy
on:
  release:
    types:
      - created
      - edited
  
  # Allows running this workflow manually on GitHub
  workflow_dispatch:

jobs:

  # Build for Windows
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up flutter environment
        uses: subosito/flutter-action@v1 # v2 struggles reading version
        with:
          flutter-version: '3.7.x'
          channel: 'stable'
      
      - name: Resolve dependecies
        run: |
          cd flutter_app
          flutter pub get
      
      - name: Build for Windows
        run: |
          cd flutter_app
          flutter config --enable-windows-desktop
          flutter build windows --release

      - name: Pack bundle to artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle-windows-x64
          path: flutter_app\build\windows\runner\Release\
          if-no-files-found: error
      
  # Build for Linux
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install necessary packages
        run: |
          sudo apt update -y
          sudo apt install -y cmake clang ninja-build libgtk-3-dev

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up flutter environment
        uses: subosito/flutter-action@v1 # v2 struggles reading version
        with:
          flutter-version: '3.7.x'
          channel: 'stable'
      
      - name: Resolve dependecies
        run: |
          cd flutter_app
          flutter pub get

      - name: Build for Linux
        run: |
          cd flutter_app
          flutter config --enable-linux-desktop
          flutter build linux --release
      
      - name: Pack bundle to artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle-linux-x64
          path: flutter_app/build/linux/x64/release/bundle/
          if-no-files-found: error
      
  # Build for macOS
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up flutter environment
        uses: subosito/flutter-action@v1 # v2 struggles reading version
        with:
          flutter-version: '3.7.x'
          channel: 'stable'
      
      - name: Resolve dependecies
        run: |
          cd flutter_app
          flutter pub get

      - name: Build for macOS
        run: |
          cd flutter_app
          flutter config --enable-macos-desktop
          flutter build macos --release

      - name: Pack bundle to artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle-macos-x64
          path: flutter_app/build/macos/Build/Products/Release/
          if-no-files-found: error
      
  # Deploy all built apps
  deploy-all:
    runs-on: ubuntu-latest
    needs: [windows, linux, macos]
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          name: bundle-linux-x64
      
      - name: DEBUG - Display file tree
        run: ls -R

      - name: Configure pages
        uses: actions/configure-pages@v3

      - name: DEBUG - Display file tree
        run: ls -R

      - name: Upload artifacts to pages
        uses: actions/upload-pages-artifact@v2

      - name: DEBUG - Display file tree
        run: ls -R

      - name: Deploy bundles on pages
        id: deployment
        uses: actions/deploy-pages@v2
      
