# Build the app for Windows, Linux and macOS

name: build
on:
  release:
    types:
      - created
      - edited
  
  # Allows running this workflow manually on GitHub
  workflow_dispatch:

jobs:

  # Build for Windows
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up flutter environment
        uses: subosito/flutter-action@v1 # v2 struggles reading version
        with:
          flutter-version: '3.7.x'
          channel: 'stable'
      
      - name: Resolve dependecies
        run: |
          cd flutter_app
          flutter pub get
      
      - name: Build for Windows
        run: |
          cd flutter_app
          flutter config --enable-windows-desktop
          flutter build windows --release

  # Build for Linux
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install necessary packages
        run: |
          sudo apt update -y
          sudo apt install -y cmake clang ninja-build libgtk-3-dev

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up flutter environment
        uses: subosito/flutter-action@v1 # v2 struggles reading version
        with:
          flutter-version: '3.7.x'
          channel: 'stable'
      
      - name: Resolve dependecies
        run: |
          cd flutter_app
          flutter pub get

      - name: Build for Linux
        run: |
          cd flutter_app
          flutter config --enable-linux-desktop
          flutter build linux --release

  # Build for macOS
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up flutter environment
        uses: subosito/flutter-action@v1 # v2 struggles reading version
        with:
          flutter-version: '3.7.x'
          channel: 'stable'
      
      - name: Resolve dependecies
        run: |
          cd flutter_app
          flutter pub get

      - name: Build for macOS
        run: |
          cd flutter_app
          flutter config --enable-macos-desktop
          flutter build macos --release
