name: Build and publish bundle

# This workflow runs on each version tag
on:
  push:
    tags:
      - "v*"
    branches:
      - "feature/*" # Only for debugging this workflow

jobs:
  release:
    runs-on: windows-latest

    env:
      App_Packages_Directory: AppPackages                   # Directory name to  store released packages
      SigningCertificate: FileTreeHasher_TemporaryKey.pfx   # Name of temporary generated key file (Get key from secrets.Base64_Encoded_Pfx)
      Solution_Path: FileTreeHasher.sln                     # Path to solution file (From repos root)
      Uwp_Project_Directory: FileTreeHasher                 # Directory of UWP to build (From repos root)
      Bundle_Architectures: x64|x86|arm|arm64               # Architectures to build bundle for
      Target_Architecture: x64                              # Architeccture of machine to build bundles at
    
    steps:
    - name: Get tag
      id: tag
      # uses: dawidd6/action-get-tag@v1
      run: echo '::set-output name=tag::v0.0.0'
    
    - name: Use tag
      run: echo ${{steps.tag.outputs.tag}}
    
    - name: Get version from tag name
      uses: Amadevus/pwsh-script@v1
      id: version
      with:
        script: '(("${{steps.tag.outputs.tag}}").Split("v")[1]+".0.0.0.0").Split(".")[0]+"."+(("${{steps.tag.outputs.tag}}").Split("v")[1]+".0.0.0.0").Split(".")[1]+"."+(("${{steps.tag.outputs.tag}}").Split("v")[1]+".0.0.0.0").Split(".")[2]+"."+(("${{steps.tag.outputs.tag}}").Split("v")[1]+".0.0.0.0").Split(".")[3]'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Update manifest version
      run: |
        [xml]$manifest = get-content ".\$env:Uwp_Project_Directory\Package.appxmanifest"
        $manifest.Package.Identity.Version = "${{steps.version.outputs.result}}"
        $manifest.save(".\$env:Uwp_Project_Directory\Package.appxmanifest")

    - name: Decode the Pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{secrets.Base64_Encoded_Pfx}}")
        $currentDirectory = Get-Location
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath $env:Uwp_Project_Directory -AdditionalChildPath $env:SigningCertificate
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    - name: Build solution
      run: msbuild $env:Solution_Path /p:Platform=$env:Target_Architecture /p:AppxBundle=$env:AppxBundle /p:AppxBundlePlatforms="$env:Bundle_Architectures" /p:AppxPackageDir=$env:App_Packages_Directory /p:PackageCertificateKeyFile=$env:SigningCertificate /restore
      env:
        AppxBundle: Always
        BuildMode: StoreUpload
        Configuration: Release
    
    - name: Remove the .pfx
      if: always()
      run: Remove-Item -path $env:Uwp_Project_Directory\$env:SigningCertificate

    - name: Archive installation bundle
      uses: actions/upload-artifact@v3
      with:
        name: Setup_bundle
        path: ${{env.Uwp_Project_Directory}}\${{env.App_Packages_Directory}}\${{env.Uwp_Project_Directory}}_${{steps.version.outputs.result}}_Test\*

# ==================== DEBUGGING ====================

    - name: Test - List file tree
      if: always()
      run: tree /a /f > FileTree.txt
    
    - name: Archive file tree view
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Debug_FileTree
        path: FileTree.txt
