name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get tag name
      id: get-tag-name
      run: echo "out=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"

    - name: Get tag message
      id: get-tag-message
      run: |
        TAG_MSG=$(git tag -l --format='%(contents)' ${{ steps.get-tag-name.outputs.out }})
        echo "TAG_MSG<<EOF" >> $GITHUB_ENV
        echo "$TAG_MSG" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get-tag-name.outputs.out }}
        release_name: ${{ steps.get-tag-name.outputs.out }}
        body: ${{ env.TAG_MSG }}
        draft: false
        prerelease: false
